language: node_js
node_js:
  - 13

services:
  - docker

stage:
  - user
  - feed
  - frontend

jobs:
  include:
    - stage: user
      name: "user backend service"
      script:
        - npm run build
        - docker --version # print the version for logging
        - docker build -t udagram-api-user .
        - docker tag udagram-api-user travisparma/udagram-udacity-project:latest
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push travisparma/udagram-udacity-project
        
    - stage: feed
      name: "feed backend service"
      script:
        - npm run build
        - docker --version # print the version for logging
        - docker build -t udagram-api-feed .
        - docker tag udagram-api-feed travisparma/udagram-udacity-project:latest
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push travisparma/udagram-udacity-project