language: node_js
node_js:
  - 13

services:
  - docker

stage:
  - user
  - feed
  # - frontend

jobs:
  include:
    - stage: user
      name: "user backend service"
      script:
        - docker --version # print the version for logging
        - docker build -t udagram-api-user ./udagram-api-user
        - docker tag udagram-api-user "$DOCKER_USERNAME"/udagram-api-user:latest
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/udagram-api-user
        
    - stage: feed
      name: "feed backend service"
      script:
        - docker --version # print the version for logging
        - docker build -t udagram-api-feed ./udagram-api-feed
        - docker tag udagram-api-feed "$DOCKER_USERNAME"/udagram-api-feed:latest
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push "$DOCKER_USERNAME"/udagram-api-feed